extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc:
      http:

  opencensus:

  jaeger:
    protocols:
      grpc:
      thrift_binary:
      thrift_compact:
      thrift_http:

  zipkin:

  # Collect own metrics
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 10s
          static_configs:
            - targets: [ '0.0.0.0:8888' ]

processors:
  batch:
  metricstransform:
    transforms:
        - action: update
          operations:
            - action: add_label
              new_label: cluster
              new_value: $MY_CLUSTER_NAME
            - action: add_label
              new_label: __replica__
              new_value: $MY_POD_NAME


exporters:
  logging:
    logLevel: debug

service:

  pipelines:

    # traces:
    #   receivers: [otlp, opencensus, jaeger, zipkin]
    #   processors: [batch]
    #   exporters: [logging]

    metrics:
      receivers: [prometheus]
      processors: [metricstransform]
      exporters: [logging]

  extensions: [health_check, pprof, zpages]
