---
# create cwagent service account and role binding
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otelcol-admin
  namespace: otelcol

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: otelcol-admin-role
rules:
  - apiGroups: [""]
    resources:
    - nodes
    - nodes/proxy
    - nodes/metrics
    - services
    - endpoints
    - pods
    - ingresses
    - configmaps
    verbs: ["get", "list", "watch"]
  - apiGroups:
    - extensions
    - networking.k8s.io
    resources:
    - ingresses
    - ingresses/status
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: otelcol-admin-role-binding
subjects:
  - kind: ServiceAccount
    name: otelcol-admin
    namespace: otelcol
roleRef:
  kind: ClusterRole
  name: otelcol-admin-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox-exporter-deployment
  namespace: otelcol
  labels:
    app: blackbox-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackbox-exporter
  template:
    metadata:
      labels:
        app: blackbox-exporter
    spec:
      serviceAccountName: default
      containers:
      - name: blackbox-exporter-cont
        image: prom/blackbox-exporter
        ports:
        - name: web
          containerPort: 9115
---
apiVersion: v1
kind: Service
metadata:
  name: blackbox-exporter-service
  namespace: otelcol
  labels:
    app: blackbox-exporter
spec:
  ports:
  - name: web
    port: 9115
    targetPort: 9115
    protocol: TCP
  selector:
    app: blackbox-exporter
  type: NodePort
---