---
# create cwagent service account and role binding
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otelcol-admin
  namespace: otelcol

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: otelcol-admin-role-binding
subjects:
  - kind: ServiceAccount
    name: otelcol-admin
    namespace: otelcol
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---