name: build-and-test
on:
  push:
    branches: [MigratePublishToGHA]
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  pull_request:

jobs:
  windows-test:
    runs-on: windows-latest
    env:
      TEST_RESULTS: testbed/tests/results/junit/results.xml
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.15
      - name: Setup Environment
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: restore module cache
        uses: actions/cache@v2
        env:
          cache-name: cache-go-modules
        with:
          path: \Users\runneradmin\go\pkg\mod
          key: go-pkg-mod-${{ runner.os }}-${{ hashFiles('./go.mod') }}
      - name: Run Unit tests
        run: go test ./...
      - name: GitHub issue generator
        if: ${{ failure() && github.ref == 'ref/head/master' }}
        run: |
          go run cmd/issuegenerator/main.go $TEST_RESULTS
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '9'
      - name: Check links in markdown docs
        run: |
          pushd $HOME
          npm install --save-dev markdown-link-check@3.8.1
          popd
      - run: ./.github/workflows/check-links/check-links.sh
  setup-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.15
      - name: Setup Environment
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Install tools
        run: make install-tools
      - name: Add Execute Permissions to Binaries
        run: chmod -R +x /home/runner/go/bin
      - name: Create Tool Binaries Archive
        run: tar -cvf tool-bin.tar /home/runner/go/bin
      - name: Upload Tool Binaries
        uses: actions/upload-artifact@v2
        with:
          name: tool-binaries
          path: ./tool-bin.tar
  lint:
    runs-on: ubuntu-latest
    needs: [setup-environment]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.15
      - name: Setup Environment
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: restore module cache
        uses: actions/cache@v2
        env:
          cache-name: cache-go-modules
        with:
          path: /home/runner/go/pkg/mod
          key: go-pkg-mod-${{ runner.os }}-${{ hashFiles('./go.mod') }}
      - name: Download Tool Binaries
        uses: actions/download-artifact@v2
        with:
          name: tool-binaries
      - name: Extract Tool Binaries Archive
        run: tar -xvf tool-bin.tar -C /
      - name: Lint
        run: make -j4 gochecklicense goimpi golint gomisspell
      - name: Gen Metadata
        run: make genmdata
      - name: Check generated metadata
        run: git diff --exit-code || (echo 'Generated code is out of date, please run "make genmdata" and commit the changes in this PR.' && exit 1)
  cross-compile:
    runs-on: ubuntu-latest
    needs: [setup-environment]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.15
      - name: Setup Environment
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: restore module cache
        uses: actions/cache@v2
        env:
          cache-name: cache-go-modules
        with:
          path: /home/runner/go/pkg/mod
          key: go-pkg-mod-${{ runner.os }}-${{ hashFiles('./go.mod') }}
      - name: Download Tool Binaries
        uses: actions/download-artifact@v2
        with:
          name: tool-binaries
      - name: Extract Tool Binaries Archive
        run: tar -xvf tool-bin.tar -C /
      - name: Build collector for all archs
        run: grep ^binaries-all-sys Makefile|fmt -w 1|tail -n +2|xargs make
      - name: Add Execute Permissions to Binaries
        run: chmod -R +x ./bin
      - name: Create Collector Binaries Archive
        run: tar -cvf bin.tar ./bin
      - name: Upload Collector Binaries
        uses: actions/upload-artifact@v2
        with:
          name: collector-binaries
          path: ./bin.tar
  build-package:
    runs-on: ubuntu-latest
    needs: [cross-compile]
    strategy:
      fail-fast: false
      matrix:
        package_type: ["deb", "rpm"]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.15
      - name: Setup Environment
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
          mkdir bin/
      - name: Install Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Install fpm and dependencies
        run: gem install --no-document fpm -v 1.11.0
      - name: Download Tool Binaries
        uses: actions/download-artifact@v2
        with:
          name: tool-binaries
      - name: Download Collector Binaries
        uses: actions/download-artifact@v2
        with:
          name: collector-binaries
      - name: Extract Binaries Archive
        run: |
          tar -xvf tool-bin.tar -C /
          tar -xvf bin.tar
      - name: Set Release Tag
        id: github_tag
        run: ./.github/workflows/scripts/set_release_tag.sh
      - name: Build ${{ matrix.package_type }} amd64 package
        run: ./internal/buildscripts/packaging/fpm/${{ matrix.package_type }}/build.sh "${{ steps.github_tag.outputs.tag }}" "amd64" "./dist/"
      - name: Build ${{ matrix.package_type }} arm64 package
        run: ./internal/buildscripts/packaging/fpm/${{ matrix.package_type }}/build.sh "${{ steps.github_tag.outputs.tag }}" "arm64" "./dist/"
      - name: Test ${{ matrix.package_type }} package
        run: |
          if [[ "${{ matrix.package_type }}" = "deb" ]]; then
              ./internal/buildscripts/packaging/fpm/test.sh dist/otel-collector*amd64.deb
          else
              ./internal/buildscripts/packaging/fpm/test.sh dist/otel-collector*x86_64.rpm
          fi
      - name: Upload Packages
        uses: actions/upload-artifact@v2
        with:
          name: build-packages
          path: ./dist
  windows-msi:
    runs-on: windows-latest
    needs: [cross-compile]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.15
      - name: Setup env
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Download Binaries
        uses: actions/download-artifact@v2
        with:
          name: collector-binaries
      - name: Extract Binaries Archive
        run: tar -xvf bin.tar
      - name: Install Wix Toolset
        run: .\internal\buildscripts\packaging\msi\make.ps1 Install-Tools
      - name: Build MSI
        run: |
          $Version = if ($env:GITHUB_REF -match '^refs/tags/(\d+\.\d+\.\d+)') { $Matches[1] } else { "0.0.1" }
          .\internal\buildscripts\packaging\msi\make.ps1 New-MSI -Version $Version
      # - name: Validate MSI
      #   run: .\internal\buildscripts\packaging\msi\make.ps1 Confirm-MSI
      - name: Upload MSI
        uses: actions/upload-artifact@v2
        with:
          name: msi-binaries
          path: ./dist/*.msi
  publish-dev:
    runs-on: ubuntu-latest
    needs: [build-package, windows-msi]
    # if: (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')) && github.repository == 'open-telemetry/opentelemetry-collector'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.15
      - name: Setup Environment
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
          mkdir bin/
      - name: Download Tool Binaries
        uses: actions/download-artifact@v2
        with:
          name: tool-binaries
      - name: Extract Tool Binaries Archive
        run: tar -xvf tool-bin.tar -C /
      - name: Download Packages
        uses: actions/download-artifact@v2
        with:
          name: build-packages
          path: ./dist
      - name: Download MSI Packages
        uses: actions/download-artifact@v2
        with:
          name: msi-binaries
          path: ./dist
      - name: Add Execute Permissions to Binaries
        run: chmod -R +x ./dist
      - name: Verify Distribution Files Exist
        id: check
        run: ./.github/workflows/scripts/verify-dist-files-exist.sh
      - name: Build Docker Image
        if: ${{ steps.check.outputs.passed }}
        run: |
            make docker-otelcol
            docker tag otelcol:latest shovnik/deploy-test:$GITHUB_SHA
            docker tag otelcol:latest shovnik/deploy-test:latest
      - name: Push Docker Image
        if: ${{ steps.check.outputs.passed }}
        run: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push shovnik/deploy-test:$GITHUB_SHA
            docker push shovnik/deploy-test:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD}}
  publish-stable:
    runs-on: ubuntu-latest
    needs: [build-package, windows-msi]
    # if: startsWith(github.ref, 'refs/tags/') && github.repository == 'open-telemetry/opentelemetry-collector'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.15
      - name: Download Tool Binaries
        uses: actions/download-artifact@v2
        with:
          name: tool-binaries
      - name: Extract Tool Binaries Archive
        run: tar -xvf tool-bin.tar -C /
      - name: Download Packages
        uses: actions/download-artifact@v2
        with:
          name: build-packages
          path: ./dist
      - name: Download MSI Packages
        uses: actions/download-artifact@v2
        with:
          name: msi-binaries
          path: ./dist
      - name: Add Execute Permissions to Binaries
        run: chmod -R +x ./dist
      - name: Verify Distribution Files Exist
        id: check
        run: ./.github/workflows/scripts/verify-dist-files-exist.sh
      - name: Build Docker Image
        if: ${{ steps.check.outputs.passed }}
        run: |
            make docker-otelcol
            docker tag otelcol:latest shovnik/deploy-test:$GITHUB_SHA
            docker tag otelcol:latest shovnik/deploy-test:latest
      - name: Push Docker Image
        if: ${{ steps.check.outputs.passed }}
        run: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker push shovnik/deploy-test:$GITHUB_SHA
            docker push shovnik/deploy-test:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD}}
      - name: Set Release Tag
        id: github_tag
        run: ./.github/workflows/scripts/set_release_tag.sh
      - name: Create Github Release
        if: ${{ steps.check.outputs.passed }}
        run: |
          cp bin/* dist/
          cd dist && shasum -a 256 * > checksums.txt
          ghr -t $GITHUB_TOKEN -u "GitHub Action" -r opentelemetry-collector --replace $RELEASE_TAG dist/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG: ${{ steps.github_tag.outputs.tag }}